name: linux

on:
  schedule:
    - cron:  '45 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lisp: [sbcl-bin/2.3.5]
        target: [x86-64]
        action: [mirror-upload]
    steps:
      - uses: actions/checkout@v3
      - name: setenv
        run: |
          echo "$HOME/.roswell/bin" >> $GITHUB_PATH
          echo "ROSWELL_BRANCH=release" >> $GITHUB_ENV
      - name: checkenv
        run: |
          uname -s
          uname -m
          echo $ROSWELL_INSTALL_DIR
          echo $ROSWELL_BRANCH
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          ros checkout log4cl
          ros install ultralisp/quickdist
      - name: mirror
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ACTION: ${{ matrix.action }}
        run: |
          echo $REPOSITORY
          ros -s cl-toml \
              -e '(defvar *hash* (cl-toml:parse-file "config.toml"))' \
              -e '(setf (gethash "github" (gethash "upload" *hash*)) (uiop:getenv "REPOSITORY"))' \
              -e '(with-open-file (o "config.toml" :direction :output :if-exists :supersede) (cl-toml:encode *hash* o))'
          cat config.toml
          make $ACTION
